general--projectFolder: projects
codeEditing--tabSizeInSpaces: 4
terminal--scrollMultiplier: 1.8
debugOptions--allowDebug: false
general--lastOpened: [/home/tapeline/JavaProjects/Files/HummingbirdFx/testProj]
appearance--fontName: JetBrains Mono
general--runConfigurations: []
general--pluginFolder: plugins
appearance--fontSize: 16
appearance--theme: Darcula
general--enabledPlugins: []
